# Generated by Django 4.2.20 on 2025-04-09 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crime_reporting_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crimerecord",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crime_reporting_app.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="crimerecord",
            name="status",
            field=models.CharField(
                choices=[("crime", "Crime"), ("corruption", "Corruption")],
                default="crime",
                max_length=20,
            ),
        ),
    ]
