# Generated by Django 4.2.20 on 2025-04-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crime_reporting_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
