# Generated by Django 4.2.20 on 2025-04-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crime_reporting_app", "0002_alter_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crimerecord",
            name="report_anonymously",
            field=models.BooleanField(default=False),
        ),
    ]
